// Enum values for GPIOs
// This is manually updated to have an appropriate name in Berry
// Convert using `python3 gpio_convert.py`

LOW
HIGH

INPUT
OUTPUT
PULLUP
INPUT_PULLUP
PULLDOWN
INPUT_PULLDOWN
OPEN_DRAIN
OUTPUT_OPEN_DRAIN
DAC = -1           // special case

RISING
FALLING
CHANGE

MAX_RMT

MAX_GPIO = MAX_GPIO_PIN

NONE = GPIO_NONE
KEY1 = GPIO_KEY1
KEY1_NP = GPIO_KEY1_NP
KEY1_INV = GPIO_KEY1_INV
KEY1_INV_NP = GPIO_KEY1_INV_NP
SWT1 = GPIO_SWT1
SWT1_NP = GPIO_SWT1_NP
REL1 = GPIO_REL1
REL1_INV = GPIO_REL1_INV
LED1 = GPIO_LED1
LED1_INV = GPIO_LED1_INV
CNTR1 = GPIO_CNTR1
CNTR1_NP = GPIO_CNTR1_NP
PWM1 = GPIO_PWM1
PWM1_INV = GPIO_PWM1_INV
BUZZER = GPIO_BUZZER
BUZZER_INV = GPIO_BUZZER_INV
LEDLNK = GPIO_LEDLNK
LEDLNK_INV = GPIO_LEDLNK_INV
I2C_SCL = GPIO_I2C_SCL
I2C_SDA = GPIO_I2C_SDA
SPI_MISO = GPIO_SPI_MISO
SPI_MOSI = GPIO_SPI_MOSI
SPI_CLK = GPIO_SPI_CLK
SPI_CS = GPIO_SPI_CS
SPI_DC = GPIO_SPI_DC
SSPI_MISO = GPIO_SSPI_MISO
SSPI_MOSI = GPIO_SSPI_MOSI
SSPI_SCLK = GPIO_SSPI_SCLK
SSPI_CS = GPIO_SSPI_CS
SSPI_DC = GPIO_SSPI_DC
BACKLIGHT = GPIO_BACKLIGHT
OLED_RESET = GPIO_OLED_RESET
RFSEND = GPIO_RFSEND
RFRECV = GPIO_RFRECV
DHT11 = GPIO_DHT11
DHT22 = GPIO_DHT22
SI7021 = GPIO_SI7021
MS01 = GPIO_MS01
DHT11_OUT = GPIO_DHT11_OUT
DSB = GPIO_DSB
DSB_OUT = GPIO_DSB_OUT
MHZ_TXD = GPIO_MHZ_TXD
MHZ_RXD = GPIO_MHZ_RXD
CM11_TXD = GPIO_CM11_TXD
CM11_RXD = GPIO_CM11_RXD
SAIR_TX = GPIO_SAIR_TX
SAIR_RX = GPIO_SAIR_RX
PMS5003_TX = GPIO_PMS5003_TX
PMS5003_RX = GPIO_PMS5003_RX
SDS0X1_TX = GPIO_SDS0X1_TX
SDS0X1_RX = GPIO_SDS0X1_RX
SBR_TX = GPIO_SBR_TX
SBR_RX = GPIO_SBR_RX
SR04_TRIG = GPIO_SR04_TRIG
SR04_ECHO = GPIO_SR04_ECHO
ME007_TRIG = GPIO_ME007_TRIG
ME007_RX = GPIO_ME007_RX
MP3_DFR562 = GPIO_MP3_DFR562
HX711_SCK = GPIO_HX711_SCK
HX711_DAT = GPIO_HX711_DAT
TX2X_TXD_BLACK = GPIO_TX2X_TXD_BLACK
MGC3130_XFER = GPIO_MGC3130_XFER
MGC3130_RESET = GPIO_MGC3130_RESET
RF_SENSOR = GPIO_RF_SENSOR
AZ_TXD = GPIO_AZ_TXD
AZ_RXD = GPIO_AZ_RXD
MAX31855CS = GPIO_MAX31855CS
MAX31855CLK = GPIO_MAX31855CLK
MAX31855DO = GPIO_MAX31855DO
PN532_TXD = GPIO_PN532_TXD
PN532_RXD = GPIO_PN532_RXD
TXD = GPIO_TXD
RXD = GPIO_RXD
ROT1A = GPIO_ROT1A
ROT1B = GPIO_ROT1B
ADC_JOY = GPIO_ADC_JOY
SSPI_MAX31865_CS1 = GPIO_SSPI_MAX31865_CS1
HRE_CLOCK = GPIO_HRE_CLOCK
HRE_DATA = GPIO_HRE_DATA
ZIGBEE_TX = GPIO_ZIGBEE_TX
ZIGBEE_RX = GPIO_ZIGBEE_RX
RDM6300_RX = GPIO_RDM6300_RX
IBEACON_TX = GPIO_IBEACON_TX
IBEACON_RX = GPIO_IBEACON_RX
A4988_DIR = GPIO_A4988_DIR
A4988_STP = GPIO_A4988_STP
A4988_ENA = GPIO_A4988_ENA
A4988_MS1 = GPIO_A4988_MS1
OUTPUT_HI = GPIO_OUTPUT_HI
OUTPUT_LO = GPIO_OUTPUT_LO
DEEPSLEEP = GPIO_DEEPSLEEP
TASMOTACLIENT_TXD = GPIO_TASMOTACLIENT_TXD
TASMOTACLIENT_RXD = GPIO_TASMOTACLIENT_RXD
TASMOTACLIENT_RST = GPIO_TASMOTACLIENT_RST
TASMOTACLIENT_RST_INV = GPIO_TASMOTACLIENT_RST_INV
HPMA_RX = GPIO_HPMA_RX
HPMA_TX = GPIO_HPMA_TX
GPS_RX = GPIO_GPS_RX
GPS_TX = GPIO_GPS_TX
HM10_RX = GPIO_HM10_RX
HM10_TX = GPIO_HM10_TX
CC1101_GDO0 = GPIO_CC1101_GDO0
CC1101_GDO2 = GPIO_CC1101_GDO2
HRXL_RX = GPIO_HRXL_RX
AS3935 = GPIO_AS3935
ADC_INPUT = GPIO_ADC_INPUT
ADC_TEMP = GPIO_ADC_TEMP
ADC_LIGHT = GPIO_ADC_LIGHT
ADC_BUTTON = GPIO_ADC_BUTTON
ADC_BUTTON_INV = GPIO_ADC_BUTTON_INV
ADC_RANGE = GPIO_ADC_RANGE
ADC_CT_POWER = GPIO_ADC_CT_POWER
WEBCAM_PWDN = GPIO_WEBCAM_PWDN
WEBCAM_RESET = GPIO_WEBCAM_RESET
WEBCAM_XCLK = GPIO_WEBCAM_XCLK
WEBCAM_SIOD = GPIO_WEBCAM_SIOD
WEBCAM_SIOC = GPIO_WEBCAM_SIOC
WEBCAM_DATA = GPIO_WEBCAM_DATA
WEBCAM_VSYNC = GPIO_WEBCAM_VSYNC
WEBCAM_HREF = GPIO_WEBCAM_HREF
WEBCAM_PCLK = GPIO_WEBCAM_PCLK
WEBCAM_PSCLK = GPIO_WEBCAM_PSCLK
WEBCAM_HSD = GPIO_WEBCAM_HSD
WEBCAM_PSRCS = GPIO_WEBCAM_PSRCS
BOILER_OT_RX = GPIO_BOILER_OT_RX
BOILER_OT_TX = GPIO_BOILER_OT_TX
WINDMETER_SPEED = GPIO_WINDMETER_SPEED
KEY1_TC = GPIO_KEY1_TC
TCP_TX = GPIO_TCP_TX
TCP_RX = GPIO_TCP_RX
TCP_TX_EN  = GPIO_TCP_TX_EN
ETH_PHY_POWER = GPIO_ETH_PHY_POWER
ETH_PHY_MDC = GPIO_ETH_PHY_MDC
ETH_PHY_MDIO = GPIO_ETH_PHY_MDIO
LMT01 = GPIO_LMT01
ZIGBEE_RST = GPIO_ZIGBEE_RST
DYP_RX = GPIO_DYP_RX
MIEL_HVAC_TX = GPIO_MIEL_HVAC_TX
MIEL_HVAC_RX = GPIO_MIEL_HVAC_RX
TUYAMCUBR_TX = GPIO_TUYAMCUBR_TX
TUYAMCUBR_RX = GPIO_TUYAMCUBR_RX
AS608_TX = GPIO_AS608_TX
AS608_RX = GPIO_AS608_RX
RC522_RST = GPIO_RC522_RST
OPTION_A = GPIO_OPTION_A
FTC532 = GPIO_FTC532
RC522_CS = GPIO_RC522_CS
NRF24_CS = GPIO_NRF24_CS
NRF24_DC = GPIO_NRF24_DC
ILI9341_CS = GPIO_ILI9341_CS
ILI9341_DC = GPIO_ILI9341_DC
SSD1351_CS = GPIO_SSD1351_CS
ST7789_CS = GPIO_ST7789_CS
ST7789_DC = GPIO_ST7789_DC
SSD1331_CS = GPIO_SSD1331_CS
SSD1331_DC = GPIO_SSD1331_DC
SDCARD_CS = GPIO_SDCARD_CS
ROT1A_NP = GPIO_ROT1A_NP
ROT1B_NP = GPIO_ROT1B_NP
ADC_PH = GPIO_ADC_PH
BS814_CLK = GPIO_BS814_CLK
BS814_DAT = GPIO_BS814_DAT
WIEGAND_D0 = GPIO_WIEGAND_D0
WIEGAND_D1 = GPIO_WIEGAND_D1
NEOPOOL_TX = GPIO_NEOPOOL_TX
NEOPOOL_RX = GPIO_NEOPOOL_RX
PROJECTOR_CTRL_TX = GPIO_PROJECTOR_CTRL_TX
PROJECTOR_CTRL_RX = GPIO_PROJECTOR_CTRL_RX
SSD1351_DC = GPIO_SSD1351_DC
XPT2046_CS = GPIO_XPT2046_CS
VL53LXX_XSHUT1 = GPIO_VL53LXX_XSHUT1
TFMINIPLUS_TX = GPIO_TFMINIPLUS_TX
TFMINIPLUS_RX = GPIO_TFMINIPLUS_RX
HALLEFFECT = GPIO_HALLEFFECT
EPD_DATA = GPIO_EPD_DATA
GPIO_INPUT = GPIO_INPUT     // avoid conflict with INPUT
KEY1_PD = GPIO_KEY1_PD
KEY1_INV_PD = GPIO_KEY1_INV_PD
SWT1_PD = GPIO_SWT1_PD
I2S_OUT_DATA = GPIO_I2S_DOUT
I2S_OUT_CLK = GPIO_I2S_BCLK
I2S_OUT_SLCT = GPIO_I2S_WS
I2S_IN_DATA = GPIO_I2S_DIN
I2S_IN_CLK = GPIO_I2S_BCLK_IN
I2S_IN_SLCT = GPIO_I2S_WS_IN
INTERRUPT = GPIO_INTERRUPT

MCP2515_CS = GPIO_MCP2515_CS

HRG15_TX = GPIO_HRG15_TX, HRG15_RX = GPIO_HRG15_RX
VINDRIKTNING_RX = GPIO_VINDRIKTNING_RX
HM330X_SET = GPIO_HM330X_SET
HEARTBEAT = GPIO_HEARTBEAT
HEARTBEAT_INV = GPIO_HEARTBEAT_INV

SHIFT595_SRCLK = GPIO_SHIFT595_SRCLK
SHIFT595_RCLK = GPIO_SHIFT595_RCLK
SHIFT595_OE = GPIO_SHIFT595_OE
SHIFT595_SER = GPIO_SHIFT595_SER
OPTION_E = GPIO_OPTION_E
ADC_MQ = GPIO_ADC_MQ
CM11_TXD = GPIO_CM11_TXD
CM11_RXD = GPIO_CM11_RXD
ADE7880_IRQ = GPIO_ADE7880_IRQ
RESET = GPIO_RESET
MS01 = GPIO_MS01
SDIO_CMD = GPIO_SDIO_CMD
SDIO_CLK = GPIO_SDIO_CLK
SDIO_D0 = GPIO_SDIO_D0
SDIO_D1 = GPIO_SDIO_D1
SDIO_D2 = GPIO_SDIO_D2
SDIO_D3 = GPIO_SDIO_D3

FLOWRATEMETER_SIGNAL = GPIO_FLOWRATEMETER_IN
MP3_DFR562_BUSY = GPIO_MP3_DFR562_BUSY
REL1_BI = GPIO_REL1_BI
REL1_BI_INV = GPIO_REL1_BI_INV
I2S_MCLK = GPIO_I2S_MCLK
MBR_TX = GPIO_MBR_TX
MBR_RX = GPIO_MBR_RX
LOX_O2_RX = GPIO_LOX_O2_RX
GM861_TX = GPIO_GM861_RX
DINGTIAN_OE = GPIO_DINGTIAN_OE
HDMI_CEC = GPIO_HDMI_CEC
HC8_RXD = GPIO_HC8_RXD
I2S_DAC = GPIO_I2S_DAC
MAGIC_SWITCH = GPIO_MAGIC_SWITCH
PIPSOLAR_TX = GPIO_PIPSOLAR_TX
PIPSOLAR_RX = GPIO_PIPSOLAR_RX

LORA_CS    = GPIO_LORA_CS
LORA_RST   = GPIO_LORA_RST
LORA_BUSY  = GPIO_LORA_BUSY
LORA_DI0   = GPIO_LORA_DI0
LORA_DI1   = GPIO_LORA_DI1
LORA_DI2   = GPIO_LORA_DI2
LORA_DI3   = GPIO_LORA_DI3
LORA_DI4   = GPIO_LORA_DI4
LORA_DI5   = GPIO_LORA_DI5

TS_SPI_CS  = GPIO_TS_SPI_CS
TS_RST     = GPIO_TS_RST
TS_IRQ     = GPIO_TS_IRQ

RN2XX3_TX  = GPIO_RN2XX3_TX
RN2XX3_RX  = GPIO_RN2XX3_RX
RN2XX3_RST = GPIO_RN2XX3_RST

WOOLIIS_RX = GPIO_WOOLIIS_RX

C8_CO2_5K_TX = GPIO_C8_CO2_5K_TX
C8_CO2_5K_RX = GPIO_C8_CO2_5K_RX

SENSOR_END = GPIO_SENSOR_END
