[platformio]
default_envs                = tasmota32p4

[env:tasmota32_base]
framework               = ${common.framework}
platform                = ${common.platform}
platform_packages       = ${common.platform_packages}
board_build.filesystem  = ${common.board_build.filesystem}
custom_unpack_dir       = ${common.custom_unpack_dir}
board_build.variants_dir = ${common.board_build.variants_dir}
board                   = esp32
monitor_speed           = ${common.monitor_speed}
monitor_echo            = ${common.monitor_echo}
upload_resetmethod      = ${common.upload_resetmethod}
check_skip_packages     = ${common.check_skip_packages}
extra_scripts           = ${common.extra_scripts}
monitor_filters         = ${common.monitor_filters}
build_unflags           = ${common.build_unflags}
build_flags             = ${common.build_flags}
lib_ldf_mode            = ${common.lib_ldf_mode}
lib_compat_mode         = ${common.lib_compat_mode}
lib_extra_dirs          = ${common.lib_extra_dirs}
lib_ignore              = ${common.lib_ignore}
; Add files to Filesystem for all env (global). Remove no files entry and add a line with the file to include
; Example for adding the Partition Manager
; custom_files_upload =
; tasmota/berry/modules/Partition_Manager.tapp
custom_files_upload = no_files
 

[env:tasmota32p4-safeboot]
extends                 = env:tasmota32_base
board                   = esp32p4
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                          -ffunction-sections
                          -DFIRMWARE_SAFEBOOT
                          -DUSE_CONFIG_OVERRIDE
                          -DOTA_URL='""'
lib_extra_dirs          = lib/lib_ssl, lib/libesp32, lib/libesp32_lvgl, lib/lib_display, lib/lib_ssl, lib/lib_div
lib_ignore              = ${safeboot_flags.lib_ignore}
custom_sdkconfig  = CONFIG_SPIRAM_BOOT_HW_INIT=y
                    CONFIG_SPIRAM_PRE_CONFIGURE_MEMORY_PROTECTION=y
                    CONFIG_SPIRAM_IGNORE_NOTFOUND=y
                    CONFIG_SPIRAM_XIP_FROM_PSRAM=y
                    '# CONFIG_SPIRAM_MEMTEST is not set'
                    CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=y
                    CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY=y
;                    CONFIG_I2C_MASTER_ISR_HANDLER_IN_IRAM=y
;                    CONFIG_LCD_DSI_ISR_HANDLER_IN_IRAM=y
;                    CONFIG_UART_ISR_IN_IRAM=y
;                    CONFIG_UHCI_ISR_HANDLER_IN_IRAM=y
;                    CONFIG_UHCI_ISR_CACHE_SAFE=y
;                    CONFIG_TWAI_ISR_CACHE_SAFE=y
                    CONFIG_LCD_DSI_ISR_CACHE_SAFE=y
                    CONFIG_BT_CONTROLLER_DISABLED=y
                    CONFIG_ESP_CONSOLE_NONE=y
                    CONFIG_ESP_CONSOLE_SECONDARY_NONE=y
                    '# CONFIG_ESP_CONSOLE_UART_DEFAULT is not set'
;                    '# CONFIG_USJ_ENABLE_USB_SERIAL_JTAG is not set'
                    '# CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG is not set'
                    '# CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED is not set'
                    '# CONFIG_I2S_ISR_IRAM_SAFE is not set'
;                    CONFIG_LCD_DSI_ISR_IRAM_SAFE=y
;                    CONFIG_DMA2D_OPERATION_FUNC_IN_IRAM=y
;                    CONFIG_DMA2D_ISR_IRAM_SAFE=y
;                    CONFIG_ISP_ISR_IRAM_SAFE=y
;                    CONFIG_ISP_CTRL_FUNC_IN_IRAM=y
;                    CONFIG_TOUCH_CTRL_FUNC_IN_IRAM=y
;                    CONFIG_TOUCH_ISR_IRAM_SAFE=y
;                    CONFIG_I2C_ISR_IRAM_SAFE=y
;                    CONFIG_LWIP_EXTRA_IRAM_OPTIMIZATION=y
;                    CONFIG_LWIP_IRAM_OPTIMIZATION=y
                    CONFIG_CACHE_L2_CACHE_128KB=y
                    '# CONFIG_CACHE_L2_CACHE_256KB is not set'
                    CONFIG_CACHE_L2_CACHE_SIZE=0x20000
                    CONFIG_LWIP_LOCAL_HOSTNAME="HexaOS"
                    CONFIG_LWIP_SO_LINGER=y
                    CONFIG_LWIP_TCP_MSS=1360
                    CONFIG_TCP_MSS=1360
                    CONFIG_LWIP_TCPIP_TASK_STACK_SIZE=8192
                    CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64
                    CONFIG_LWIP_TCP_RECVMBOX_SIZE=26
                    CONFIG_LWIP_UDP_RECVMBOX_SIZE=8
                    CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65280
                    CONFIG_LWIP_TCP_WND_DEFAULT=32640
                    CONFIG_LWIP_MAX_SOCKETS=32
                    CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
                    CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=4096
                    CONFIG_ESP_INT_WDT_TIMEOUT_MS=500
                    CONFIG_INT_WDT_TIMEOUT_MS=500
                    CONFIG_ESP_TASK_WDT_TIMEOUT_S=9
                    CONFIG_TASK_WDT_TIMEOUT_S=9
                    '# CONFIG_FREERTOS_USE_TRACE_FACILITY is not set'
                    '# CONFIG_FREERTOS_INTERRUPT_BACKTRACE is not set'
                    '# CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS is not set'
                    '# CONFIG_SPIFFS_CACHE is not set'
                    '# CONFIG_SPIFFS_PAGE_CHECK is not set'
                    '# CONFIG_SPIFFS_USE_MAGIC is not set'
                    '# CONFIG_ESP_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_ESP_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_ESP_ENABLE_BT_NIMBLE is not set'
                    '# CONFIG_BT_ENABLED is not set'
                    '# CONFIG_LCD_RGB_ISR_IRAM_SAFE is not set'



[env:tasmota32p4]
extends                 = env:tasmota32_base
board                   = esp32p4
extra_scripts           = ${env:tasmota32_base.extra_scripts}
;                          pre:patches/sections.py
;                          pre:patches/sections_nones.py
;                          pre:patches/sections_nocrash.py
build_unflags           = ${env:tasmota32_base.build_unflags}
                          -Os                        
                          -flto
                          -flto=auto
build_flags             = ${env:tasmota32_base.build_flags}
                          -O3
                          -ffunction-sections
                          -fno-lto
                          ;-DFIRMWARE_TASMOTA32
                          -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32p4.bin"'
lib_ignore              = ${env:tasmota32_base.lib_ignore}
custom_files_upload     = import/
custom_sdkconfig  = CONFIG_COMPILER_OPTIMIZATION_PERF=y
                    '# CONFIG_COMPILER_OPTIMIZATION_SIZE is not set'
                    CONFIG_SPIRAM_BOOT_HW_INIT=y
                    CONFIG_SPIRAM_PRE_CONFIGURE_MEMORY_PROTECTION=y
                    CONFIG_SPIRAM_IGNORE_NOTFOUND=y
                    CONFIG_SPIRAM_XIP_FROM_PSRAM=y
                    '# CONFIG_SPIRAM_MEMTEST is not set'
                    CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=y
                    CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY=y
                    CONFIG_LCD_DSI_ISR_CACHE_SAFE=y
                    CONFIG_BT_CONTROLLER_DISABLED=y
                    CONFIG_ESP_CONSOLE_NONE=y
                    CONFIG_ESP_CONSOLE_SECONDARY_NONE=y
                    '# CONFIG_ESP_CONSOLE_UART_DEFAULT is not set'
;                    '# CONFIG_USJ_ENABLE_USB_SERIAL_JTAG is not set'
                    '# CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG is not set'
                    '# CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED is not set'
                    '# CONFIG_I2S_ISR_IRAM_SAFE is not set'
                    CONFIG_DMA2D_OPERATION_FUNC_IN_IRAM=y
;                    CONFIG_DMA2D_ISR_IRAM_SAFE=y
;                    CONFIG_ISP_ISR_IRAM_SAFE=y
;                    CONFIG_ISP_CTRL_FUNC_IN_IRAM=y
;                    CONFIG_TOUCH_CTRL_FUNC_IN_IRAM=y
;                    CONFIG_TOUCH_ISR_IRAM_SAFE=y
;                    CONFIG_I2C_ISR_IRAM_SAFE=y
;                    CONFIG_LWIP_EXTRA_IRAM_OPTIMIZATION=y
;                    CONFIG_LWIP_IRAM_OPTIMIZATION=y
                    CONFIG_CACHE_L2_CACHE_128KB=y
                    '# CONFIG_CACHE_L2_CACHE_256KB is not set'
                    CONFIG_CACHE_L2_CACHE_SIZE=0x20000
                    CONFIG_LWIP_LOCAL_HOSTNAME="HexaOS"
                    CONFIG_LWIP_SO_LINGER=y
                    CONFIG_LWIP_TCP_MSS=1360
                    CONFIG_TCP_MSS=1360
                    CONFIG_LWIP_TCPIP_TASK_STACK_SIZE=8192
                    CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64
                    CONFIG_LWIP_TCP_RECVMBOX_SIZE=26
                    CONFIG_LWIP_UDP_RECVMBOX_SIZE=8
                    CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65280
                    CONFIG_LWIP_TCP_WND_DEFAULT=32640
                    CONFIG_LWIP_MAX_SOCKETS=32
                    CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
                    CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=4096
                    CONFIG_ESP_INT_WDT_TIMEOUT_MS=500
                    CONFIG_INT_WDT_TIMEOUT_MS=500
                    CONFIG_ESP_TASK_WDT_TIMEOUT_S=9
                    CONFIG_TASK_WDT_TIMEOUT_S=9
                    '# CONFIG_FREERTOS_USE_TRACE_FACILITY is not set'
                    '# CONFIG_FREERTOS_INTERRUPT_BACKTRACE is not set'
                    '# CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS is not set'
                    '# CONFIG_SPIFFS_CACHE is not set'
                    '# CONFIG_SPIFFS_PAGE_CHECK is not set'
                    '# CONFIG_SPIFFS_USE_MAGIC is not set'
                    '# CONFIG_ESP_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_ESP_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_ESP_ENABLE_BT_NIMBLE is not set'
                    '# CONFIG_BT_ENABLED is not set'
                    '# CONFIG_LCD_RGB_ISR_IRAM_SAFE is not set'
