[platformio]
default_envs                = tasmota32p4r3




[env:tasmota32_base]
framework               = ${common.framework}
platform                = ${core32.platform}
platform_packages       = ${core32.platform_packages}
board_build.filesystem  = ${common.board_build.filesystem}
custom_unpack_dir       = ${common.custom_unpack_dir}
board_build.variants_dir = ${common.board_build.variants_dir}
board                   = esp32
monitor_speed           = ${common.monitor_speed}
monitor_echo            = ${common.monitor_echo}
upload_resetmethod      = ${common.upload_resetmethod}
check_skip_packages     = ${common.check_skip_packages}
extra_scripts           = ${esp32_defaults.extra_scripts}
monitor_filters         = ${esp32_defaults.monitor_filters}
build_unflags           = ${core32.build_unflags}
build_flags             = ${core32.build_flags}
lib_ldf_mode            = ${common.lib_ldf_mode}
lib_compat_mode         = ${common.lib_compat_mode}
lib_extra_dirs          = ${common.lib_extra_dirs}
                          lib/libesp32
                          lib/libesp32_lvgl
lib_ignore              = ${esp32_defaults.lib_ignore}
; Add files to Filesystem for all env (global). Remove no files entry and add a line with the file to include
; Example for adding the Partition Manager
; custom_files_upload =
; tasmota/berry/modules/Partition_Manager.tapp
custom_files_upload     = import/autoexec.be
                          import/display.ini


[env:tasmota32p4r3-safeboot]
;platform                = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF55_gcc15
extends                 = env:tasmota32_base
board                   = esp32p4r3
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                          -DFIRMWARE_SAFEBOOT
                          -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32p4r3-safeboot.bin"'
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}

[env:tasmota32p4r3]
;platform                = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF55_gcc15
extends                 = env:tasmota32_base
board                   = esp32p4r3
build_flags             = ${env:tasmota32_base.build_flags}
                          ;-DFIRMWARE_TASMOTA32
                          -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32p4r3.bin"'
lib_ignore              =     ${env:tasmota32_base.lib_ignore}
                              ESP Mail Client
                              IRremoteESP8266
                              NeoPixelBus
                              ESP8266Audio
                              ESP8266SAM
                              Berry Matter protocol implementation
                              Berry animation library for WS2812 leds
                              Micro-RTSP
                              Waveshare esp 2.9 inch e-paper display driver
                              Waveshare esp 4.2 inch e-paper display driver
                              Adafruit CCS811 Library
                              Adafruit MAX31865 library
                              Adafruit MCP9808 Library
                              Adafruit PM25 AQI Sensor
                              Adafruit seesaw Library
                              Adafruit SGP30 Sensor
                              Adafruit SGP40 Sensor
                              Adafruit VEML7700 Library
                              Adafruit Fingerprint Sensor Library
                              Adafruit LED Backpack Library
                              Adafruit TSL2591
                              MPU6050 I2C
                              Mutichannel_Gas_Sensor
                              ScioSense ENS16x
                              ScioSense ENS210
                              Sensirion I2C SGP41
                              SevenSegmentTM1637
                              SPL06-007
                              VL53L0X
                              VL53L1X
                              DS2480 Library
                              ESP KNX IP Library
                              FrogmoreScd30
                              FrogmoreScd40
                              HASPmota
                              TasmotaLED
                              LedControl
                              LOLIN_HP303B
                              MFRC522
                              MPU_accel
                              BlueRobotics_MS5837
                              RA8876
                              Sensirion I2C SEN5X
                              HPMA115S0 Arduino Library
                              MLX90640
                              TM1638plus
                              XPT2046_Touchscreen
                              A4988_Stepper
                              OpenTherm Library
                              ams
                              QuickEspNow
                              LibTeleinfo
                              arduino-mcp2515-1.0.1
                              Process_control
                              OneWire
                              BME68x
                              BME8563
