[platformio]
default_envs                = tasmota32p4




[env:tasmota32_base]
framework               = ${common.framework}
platform                = ${core32.platform}
platform_packages       = ${core32.platform_packages}
board_build.filesystem  = ${common.board_build.filesystem}
custom_unpack_dir       = ${common.custom_unpack_dir}
board_build.variants_dir = ${common.board_build.variants_dir}
board                   = esp32
monitor_speed           = ${common.monitor_speed}
monitor_echo            = ${common.monitor_echo}
upload_resetmethod      = ${common.upload_resetmethod}
check_skip_packages     = ${common.check_skip_packages}
extra_scripts           = ${esp32_defaults.extra_scripts}
monitor_filters         = ${esp32_defaults.monitor_filters}
build_unflags           = ${core32.build_unflags}
build_flags             = ${core32.build_flags}
lib_ldf_mode            = ${common.lib_ldf_mode}
lib_compat_mode         = ${common.lib_compat_mode}
lib_extra_dirs          = ${common.lib_extra_dirs}
                          lib/libesp32
                          lib/libesp32_lvgl
lib_ignore              = ${esp32_defaults.lib_ignore}
; Add files to Filesystem for all env (global). Remove no files entry and add a line with the file to include
; Example for adding the Partition Manager
; custom_files_upload =
; tasmota/berry/modules/Partition_Manager.tapp
custom_files_upload = no_files
 

[env:tasmota32p4-safeboot]
extends                 = env:tasmota32_base
board                   = esp32p4
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                          -DFIRMWARE_SAFEBOOT
                          -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32p4-safeboot.bin"'
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}

[env:tasmota32p4]
extends                 = env:tasmota32_base
board                   = esp32p4
extra_scripts           = ${env:tasmota32_base.extra_scripts}
;                          pre:patches/sections.py
;                          pre:patches/sections_nones.py
                          pre:patches/sections_nocrash.py
build_unflags           = ${env:tasmota32_base.build_unflags}
                            -Os
                            -ffunction-sections
build_flags             = ${env:tasmota32_base.build_flags}
                            -Ofast
                          ;-DFIRMWARE_TASMOTA32
                          -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32p4.bin"'
lib_ignore              =     ${env:tasmota32_base.lib_ignore}
                              ESP Mail Client
                              NeoPixelBus
                              ESP8266Audio
                              ESP8266SAM
                              Berry Matter protocol implementation
                              Berry animation library for WS2812 leds
                              Micro-RTSP
                              Waveshare esp 2.9 inch e-paper display driver
                              Waveshare esp 4.2 inch e-paper display driver
                              Adafruit CCS811 Library
                              Adafruit MAX31865 library
                              Adafruit MCP9808 Library
                              Adafruit PM25 AQI Sensor
                              Adafruit seesaw Library
                              Adafruit SGP30 Sensor
                              Adafruit SGP40 Sensor
                              Adafruit VEML7700 Library
                              Adafruit Fingerprint Sensor Library
                              Adafruit LED Backpack Library
                              Adafruit TSL2591
                              MPU6050 I2C
                              Mutichannel_Gas_Sensor
                              ScioSense ENS16x
                              ScioSense ENS210
                              Sensirion I2C SGP41
                              SevenSegmentTM1637
                              SPL06-007
                              VL53L0X
                              VL53L1X
                              DS2480 Library
                              ESP KNX IP Library
                              FrogmoreScd30
                              FrogmoreScd40
                              HASPmota
                              TasmotaLED
                              LedControl
                              LOLIN_HP303B
                              MFRC522
                              MPU_accel
                              BlueRobotics_MS5837
                              RA8876
                              Sensirion I2C SEN5X
                              HPMA115S0 Arduino Library
                              MLX90640
                              TM1638plus
                              XPT2046_Touchscreen
                              A4988_Stepper
                              OpenTherm Library
                              ams
                              QuickEspNow
                              LibTeleinfo
                              arduino-mcp2515-1.0.1
                              Process_control
                              OneWire
                              BME68x
                              BME8563
                              RadioLib
                              rc-switch
                              RF24
                              TasmotaDali
                              AGS02MA
                              vid6608
                              LoRa
                              EEPROM 24C128_256_521
                              DHT sensor library
                              LiquidCrystal_I2C
                              TasmotaModbus
                              ESPmDNS
                              KeeloqLib

custom_files_upload = import/
custom_sdkconfig  = CONFIG_COMPILER_OPTIMIZATION_PERF=y
                    CONFIG_I2C_MASTER_ISR_HANDLER_IN_IRAM=y
                    CONFIG_LCD_DSI_ISR_HANDLER_IN_IRAM=y
                    CONFIG_UART_ISR_IN_IRAM=y
                    CONFIG_UHCI_ISR_HANDLER_IN_IRAM=y
                    CONFIG_UHCI_ISR_CACHE_SAFE=y
                    CONFIG_LCD_DSI_ISR_CACHE_SAFE=y
                    CONFIG_BT_CONTROLLER_DISABLED=y
                    '# CONFIG_I2S_ISR_IRAM_SAFE is not set'
;                    CONFIG_LCD_DSI_ISR_IRAM_SAFE=y
                    CONFIG_DMA2D_OPERATION_FUNC_IN_IRAM=y
;                    CONFIG_DMA2D_ISR_IRAM_SAFE=y
;                    CONFIG_ISP_ISR_IRAM_SAFE=y
                    CONFIG_ISP_CTRL_FUNC_IN_IRAM=y
                    CONFIG_TOUCH_CTRL_FUNC_IN_IRAM=y
                    CONFIG_TOUCH_ISR_IRAM_SAFE=y
                    CONFIG_I2C_ISR_IRAM_SAFE=y
                    CONFIG_LWIP_EXTRA_IRAM_OPTIMIZATION=y
                    CONFIG_LWIP_IRAM_OPTIMIZATION=y
                    CONFIG_CACHE_L2_CACHE_128KB=y
                    CONFIG_CACHE_L2_CACHE_SIZE=0x20000
                    CONFIG_LWIP_LOCAL_HOSTNAME="HexaOS"
                    CONFIG_LWIP_SO_LINGER=y
                    CONFIG_LWIP_TCP_MSS=1360
                    CONFIG_TCP_MSS=1360
                    CONFIG_LWIP_TCPIP_TASK_STACK_SIZE=8192
                    CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64
                    CONFIG_LWIP_TCP_RECVMBOX_SIZE=32
                    CONFIG_LWIP_UDP_RECVMBOX_SIZE=16
                    CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65534
                    CONFIG_LWIP_TCP_WND_DEFAULT=32767
                    CONFIG_LWIP_MAX_SOCKETS=32
                    CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=98304
                    CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=4096
                    CONFIG_ESP_INT_WDT_TIMEOUT_MS=500
                    CONFIG_INT_WDT_TIMEOUT_MS=500
                    CONFIG_ESP_TASK_WDT_TIMEOUT_S=9
                    CONFIG_TASK_WDT_TIMEOUT_S=9
                    '# CONFIG_FREERTOS_USE_TRACE_FACILITY is not set'
                    '# CONFIG_FREERTOS_INTERRUPT_BACKTRACE is not set'
                    '# CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS is not set'
                    '# CONFIG_SPIFFS_CACHE is not set'
                    '# CONFIG_SPIFFS_PAGE_CHECK is not set'
                    '# CONFIG_SPIFFS_USE_MAGIC is not set'
                    '# CONFIG_ESP_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_ESP_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_GDBSTUB_SUPPORT_TASKS is not set'
                    '# CONFIG_GDBSTUB_MAX_TASKS is not set'
                    '# CONFIG_ESP_ENABLE_BT_NIMBLE is not set'
                    '# CONFIG_CACHE_L2_CACHE_256KB is not set'
                    '# CONFIG_COMPILER_OPTIMIZATION_SIZE is not set'
                    '# CONFIG_TINYUSB_VIDEO_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_VIDEO_STRING is not set'
                    '# CONFIG_TINYUSB_VIDEO_STREAMING_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_VIDEO_STREAMING_IFS is not set'
                    '# CONFIG_TINYUSB_HID_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_HID_STRING is not set'
                    '# CONFIG_TINYUSB_HID_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_MSC_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_MSC_STRING is not set'
                    '# CONFIG_TINYUSB_MSC_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_DFU_RT_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_DFU_RT_STRING is not set'
                    '# CONFIG_TINYUSB_DFU_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_DFU_STRING is not set'
                    '# CONFIG_TINYUSB_DFU_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_VENDOR_ENABLED is not set'
                    '# CONFIG_TINYUSB_DESC_VENDOR_STRING is not set'
                    '# CONFIG_TINYUSB_VENDOR_RX_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_VENDOR_TX_BUFSIZE is not set'
                    '# CONFIG_TINYUSB_NCM_ENABLED is not set'
                    '# CONFIG_BT_ENABLED is not set'
                    '# CONFIG_BT_NIMBLE_ENABLED is not set'
                    '# CONFIG_NIMBLE_ENABLED is not set'
                    '# CONFIG_WIFI_PROV_BLE_SEC_CONN is not set'
                    '# CONFIG_BT_NIMBLE_HCI_UART_FLOW_CTRL is not set'
                    '# CONFIG_BT_NIMBLE_HCI_UART_RTS_PIN is not set'
                    '# CONFIG_BT_NIMBLE_HCI_UART_CTS_PIN is not set'
                    '# CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL is not set'
                    '# CONFIG_BT_NIMBLE_PINNED_TO_CORE is not set'
                    '# CONFIG_BT_NIMBLE_PINNED_TO_CORE_0 is not set'
                    '# CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_ROLE_CENTRAL is not set'
                    '# CONFIG_BT_NIMBLE_ROLE_PERIPHERAL is not set'
                    '# CONFIG_BT_NIMBLE_ROLE_BROADCASTER is not set'
                    '# CONFIG_BT_NIMBLE_ROLE_OBSERVER is not set'
                    '# CONFIG_BT_NIMBLE_GATT_CLIENT is not set'
                    '# CONFIG_BT_NIMBLE_GATT_SERVER is not set'
                    '# CONFIG_BT_NIMBLE_SECURITY_ENABLE is not set'
                    '# CONFIG_BT_NIMBLE_SM_LEGACY is not set'
                    '# CONFIG_BT_NIMBLE_SM_SC is not set'
                    '# CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_ENCRYPTION is not set'
                    '# CONFIG_BT_NIMBLE_SM_LVL is not set'
                    '# CONFIG_BT_NIMBLE_SM_SC_ONLY is not set'
                    '# CONFIG_BT_NIMBLE_MAX_BONDS is not set'
                    '# CONFIG_BT_NIMBLE_RPA_TIMEOUT is not set'
                    '# CONFIG_BT_NIMBLE_WHITELIST_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_HS_PVCY is not set'
                    '# CONFIG_BT_NIMBLE_MAX_CONNECTIONS is not set'
                    '# CONFIG_BT_NIMBLE_MAX_CCCDS is not set'
                    '# CONFIG_BT_NIMBLE_CRYPTO_STACK_MBEDTLS is not set'
                    '# CONFIG_BT_NIMBLE_HS_STOP_TIMEOUT_MS is not set'
                    '# CONFIG_BT_NIMBLE_USE_ESP_TIMER is not set'
                    '# CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU is not set'
                    '# CONFIG_BT_NIMBLE_ATT_MAX_PREP_ENTRIES is not set'
                    '# CONFIG_BT_NIMBLE_GATT_MAX_PROCS is not set'
                    '# CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM is not set'
                    '# CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_MSYS_1_BLOCK_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_TRANSPORT_ACL_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_TRANSPORT_EVT_SIZE is not set'
                    '# CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_L2CAP_COC_SDU_BUFF_COUNT is not set'
                    '# CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT is not set'
                    '# CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_2M_PHY is not set'
                    '# CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY is not set'
                    '# CONFIG_BT_NIMBLE_EXT_SCAN is not set'
                    '# CONFIG_BT_NIMBLE_ENABLE_PERIODIC_SYNC is not set'
                    '# CONFIG_BT_NIMBLE_MAX_PERIODIC_SYNCS is not set'
                    '# CONFIG_BT_NIMBLE_PROX_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_ANS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_CTS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_HTP_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_IPSS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_TPS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_IAS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_LLS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_SPS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_HR_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_BAS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_DIS_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_GAP_SERVICE is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME is not set'
                    '# CONFIG_BT_NIMBLE_GAP_DEVICE_NAME_MAX_LEN is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_APPEARANCE is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_ENC is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHEN is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHOR is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_CAR_CHAR_NOT_SUPP is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_CENT_ADDR_RESOLUTION is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ENC is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHN is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHR is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SLAVE_LATENCY is not set'
                    '# CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SUPERVISION_TMO is not set'
                    '# CONFIG_BT_NIMBLE_EATT_CHAN_NUM is not set'
                    '# CONFIG_BT_NIMBLE_DTM_MODE_TEST is not set'
                    '# CONFIG_BT_NIMBLE_MEM_OPTIMIZATION is not set'
                    '# CONFIG_BT_NIMBLE_STATIC_TO_DYNAMIC is not set'
                    '# CONFIG_BT_NIMBLE_SM_SIGN_CNT is not set'
                    '# CONFIG_BT_NIMBLE_CPFD_CAFD is not set'
                    '# CONFIG_BT_NIMBLE_RECONFIG_MTU is not set'
                    '# CONFIG_BT_NIMBLE_LOG_LEVEL_INFO is not set'
                    '# CONFIG_BT_NIMBLE_LOG_LEVEL is not set'
                    '# CONFIG_BT_NIMBLE_PRINT_ERR_NAME is not set'
                    '# CONFIG_BT_NIMBLE_CHK_HOST_STATUS is not set'
                    '# CONFIG_BT_NIMBLE_UTIL_API is not set'
                    '# CONFIG_BT_NIMBLE_EXTRA_ADV_FIELDS is not set'
                    '# CONFIG_BT_ALARM_MAX_NUM is not set'
                    '# CONFIG_BT_SMP_CRYPTO_STACK_TINYCRYPT is not set'
                    '# CONFIG_LCD_RGB_ISR_IRAM_SAFE is not set'
                    '# CONFIG_TINYUSB_MIDI_ENABLED is not set'
                    '# CONFIG_TINYUSB_ENABLED is not set'
    
