; PlatformIO Project Configuration File
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html
;
; *********************************************************************
; *** Selection of Tasmota build variant is done with VSC
; *** alternatively can be done in: platformio_override.ini
; *** See example: platformio_override_sample.ini
; *********************************************************************
 
[platformio]
description                 = ESP32 Operating System - HexaOS
src_dir                     = tasmota
lib_dir                     = lib/default
boards_dir                  = boards
build_cache_dir             = .cache
extra_configs               = platformio_hexaos.ini

[common]
;platform                   = https://github.com/tasmota/platform-espressif32/releases/download/2026.01.30/platform-espressif32.zip
;platform                   = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF55_gcc152
;platform                   = https://github.com/tasmota/platform-espressif32/releases/download/2026.02.30/platform-espressif32.zip
;platform                   = ./platform/platform-espressif32-Arduino-IDF55_gcc152_18_02_2026.zip
;platform                   = ./platform/platform-espressif32-Arduino-IDF55_gcc152_19_02_2026_15.zip
platform                    = ./platform/platform-espressif32-Arduino-IDF55_gcc152_27_02_2026.zip
platform_packages           =
framework                   = arduino
board                       = esp32p4
board_build.filesystem      = littlefs
board_build.littlefs_version = 2.0
board_build.variants_dir    = variants/tasmota
custom_unpack_dir           = unpacked_littlefs
monitor_speed               = 115200
monitor_echo                = yes
upload_resetmethod          = nodemcu
check_skip_packages         = yes
lib_archive                 = no
lib_ldf_mode                = chain
lib_compat_mode             = strict
shared_libdeps_dir          = lib
lib_extra_dirs              = lib/lib_basic
                              lib/lib_i2c
                              lib/lib_display
                              lib/lib_ssl
 ;                             lib/lib_audio
                              lib/lib_rf
                              lib/lib_div
                              lib/libesp32
                              lib/libesp32_lvgl

build_unflags               = -Wdeprecated-declarations
                              -Wall
                              -Wswitch-unreachable
                              -Wincompatible-pointer-types
                              -Wnonnull-compare
                              -Wpointer-arith
                              -fexceptions
build_flags                 = -Wl,-Map,firmware.map
                              -Wl,--gc-sections
;                              -Wl,--wrap=panicHandler -Wl,--wrap=xt_unhandled_exception
                              -Wl,--wrap=_Z11analogWritehi  ; `analogWrite(unsigned char, int)` use the Tasmota version of analogWrite for deeper integration and phase control
                              -Wl,--wrap=ledcReadFreq       ; `uint32_t ledcReadFreq(uint8_t chan)`
                              -Wl,--wrap=delay              ; void delay(uint32_t ms)
                              -Wno-deprecated-declarations
                              -Wno-switch-unreachable
                              -Wreturn-type
                              -fno-exceptions
                              -ffunction-sections
                              -fdata-sections
                              -DCORE_DEBUG_LEVEL=0
                              -DUSE_SHA_ROM
                              -DUSE_4K_RSA
                              -DTASMOTA
                              -DUSE_CONFIG_OVERRIDE
                              -DUSE_IPV6
                              -I$PROJECT_DIR/include
                              -include "sdkconfig.h"
                              -include "esp32x_fixes.h"
                              -DBUFFER_LENGTH=128
                              -DHTTP_UPLOAD_BUFLEN=2048
                              -DMQTT_MAX_PACKET_SIZE=1200
                              -Duint32=uint32_t
                              -Duint16=uint16_t
                              -Duint8=uint8_t
                              -Dsint8_t=int8_t
                              -Dsint32_t=int32_t
                              -Dsint16_t=int16_t
                              -Dmemcpy_P=memcpy
                              -Dmemcmp_P=memcmp

lib_ignore                  = HTTPUpdateServer
                              USB
                              NetBIOS
                              Preferences
                              ArduinoOTA
                              ESP Mail Client
                              NeoPixelBus
                              IRremoteESP8266
                              EEPROM
                              ESP8266Audio
                              ESP8266SAM
                              Berry Matter protocol implementation
                              Berry animation library for WS2812 leds
                              Berry Animation Framework
                              UdpListener
                              Micro-RTSP
                              Waveshare esp 2.9 inch e-paper display driver
                              Waveshare esp 4.2 inch e-paper display driver
                              Adafruit CCS811 Library
                              Adafruit MAX31865 library
                              Adafruit MCP9808 Library
                              Adafruit PM25 AQI Sensor
                              Adafruit seesaw Library
                              Adafruit SGP30 Sensor
                              Adafruit SGP40 Sensor
                              Adafruit VEML7700 Library
                              Adafruit Fingerprint Sensor Library
                              Adafruit LED Backpack Library
                              Adafruit TSL2591
                              MPU6050 I2C
                              Mutichannel_Gas_Sensor
                              ScioSense ENS16x
                              ScioSense ENS210
                              Sensirion I2C SGP41
                              SPL06-007
                              VL53L0X
                              VL53L1X
                              DS2480 Library
                              ESP KNX IP Library
                              FrogmoreScd30
                              FrogmoreScd40
                              HASPmota
                              TasmotaLED
                              LOLIN_HP303B
                              MFRC522
                              MPU_accel
                              BlueRobotics_MS5837
                              RA8876
                              Sensirion I2C SEN5X
                              HPMA115S0 Arduino Library
                              MLX90640
                              TM1638plus
                              XPT2046_Touchscreen
                              A4988_Stepper
                              OpenTherm Library
                              ams
                              QuickEspNow
                              LibTeleinfo
                              arduino-mcp2515-1.0.1
                              Process_control
                              OneWire
                              BME68x
                              BME8563
                              RadioLib
                              rc-switch
                              RF24
                              TasmotaDali
                              AGS02MA
                              vid6608
                              LoRa
                              EEPROM 24C128_256_521
                              DHT sensor library
                              LiquidCrystal_I2C
                              TasmotaModbus
                              ESPmDNS
                              KeeloqLib

extra_scripts               = pre:pio-tools/add_c_flags.py
                              pre:pio-tools/solidify-from-url.py
                              pre:pio-tools/gen-berry-structures.py
                              post:pio-tools/post_esp32.py
                              post:pio-tools/name-firmware.py
                              post:pio-tools/gzip-firmware.py
                              post:pio-tools/metrics-firmware.py
                              pre:pio-tools/custom_target.py
;                              post:pio-tools/obj-dump.py
                              pre:pio-tools/pre_source_dir.py
                              pre:pio-tools/set_partition_table.py
                              pre:pio-tools/override_copy.py
                              pre:pio-tools/compress-html.py
                              pre:pio-tools/port-vsc.py
                              post:pio-tools/strip-flags.py
monitor_filters             = esp32_exception_decoder

[safeboot_flags]
lib_ignore                  = ${common.lib_ignore}
custom_component_remove     = espressif/network_provisioning
                              espressif/esp_modem
                              espressif/esp-dsp
                              espressif/esp32-camera
                              espressif/mdns
                              espressif/esp_jpg
                              espressif/fb_gfx
                              espressif/cmake_utilities